services:
    app:
        build:
            context: .
        command: npm run dev -- -H 0.0.0.0
        volumes:
            - .:/app
            # - /app/node_modules
            # - /app/.next
        environment:
            - NODE_ENV=development
            - NEXT_TELEMETRY_DISABLED=1
            - WATCHPACK_POLLING=true
        labels:
            - traefik.enable=true
            - traefik.docker.network=dev-net
            - traefik.http.services.crm.loadbalancer.server.port=3000
            - traefik.http.routers.crm.rule=Host(`crm.localhost`)
            - traefik.http.routers.crm.entrypoints=https
            - traefik.http.routers.crm.tls=true
            - traefik.http.routers.crm-http.rule=Host(`crm.localhost`)
            - traefik.http.routers.crm-http.entrypoints=http
            - traefik.http.routers.crm-http.middlewares=redirect-to-https
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        platform: linux/amd64 # Patch for M1 Mac
        networks:
            - dev-net

networks:
    dev-net:
        external: true
